apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-volume-pv
  namespace: nginx  # Specify the namespace here
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-volume-pvc
  namespace: nginx  # Specify the namespace here
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx  # Specify the namespace here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: host-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: host-volume
        persistentVolumeClaim:
          claimName: host-volume-pvc
