apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TalelKarim/test-argo.git
    targetRevision: master
    path: helm
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: -f values.yaml 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


