---
velero:
  namespace:
    labels: {}

  # Backup schedules to create.
  schedules:
    nginx-app-backup:
      disabled: false
      schedule: "*/2 * * * *"
      useOwnerReferencesInBackup: false
      template:
        ttl: "720h"
        storageLocation: test
        volumeSnapshotLocation: test-snapshot
        snapshotVolumes: true
        includedNamespaces:
        - nginx
        metadata:
          annotations:
             backup.velero.io/backup-volumes: pvc-volume  
          labels:
             app: "nginx-app"


  
  # Backup storage locations to create
  configuration:
    backupStorageLocation:
      - name:  test
        provider: aws
        bucket: arcons-backup
        prefix:  test
        validationFrequency:
        accessMode: ReadWrite
        default: true
        config: {
          region: fr-par,
          s3Url: https://s3.fr-par.scw.cloud
        }

    defaultBackupTTL: "720h"  # Set this to a duration greater than your schedule interval, e.g., 720 hours.
    backupSyncPeriod: "720h"
    garbageCollectionFrequency: "720h"
    logLevel: "error"
 

  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.8.2
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins

  snapshotsEnabled: false

  credentials:
    useSecret: true
    existingSecret: iam-credentials-scaleway
    secretContents:
      # cloud: |
      #   [default]
      #   aws_access_key_id=vault:kv-v2/scaleway-access#scaleway_access_key_id
      #   aws_secret_access_key=vault:kv-v2/scaleway-access#scaleway_secret_access_key
    extraEnvVars: {}
    extraSecretRef: ""


  volumeSnapshotLocation:
  - name: test-snapshot
    provider: aws
    config: 
      region: fr-par
  #    apiTimeout:
  #    resourceGroup:
  #    The ID of the subscription where volume snapshots should be stored, if different from the cluster’s subscription. If specified, also requires `configuration.volumeSnapshotLocation.config.resourceGroup`to be set. (Azure only)
  #    subscriptionId:
  #    incremental:
  #    snapshotLocation:
  #    project: